version: '3'

services:
  application:
    image: smoothbear04/dms-pms-auth:${VERSION}.RELEASE
    build: .
    ports:
      - 8080:8080
    volumes:
      - log:${LOCAL_LOGGING_PATH}
    environment:
      - DB_PMS_URL=${DB_PMS_URL}
      - DB_DMS_URL=${DB_DMS_URL}
      - DB_DMS_USERNAME=${DB_DMS_USERNAME}
      - DB_DMS_PASSWORD=${DB_DMS_PASSWORD}