spring:
  output:
    ansi:
      enabled: always
  # PMS Datasource
  datasource:
    jdbc-url: ${DB_PMS_URL}
    driver-class-name: org.postgresql.Driver

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  jpa:
    database: default
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  main:
    allow-bean-definition-overriding: true


logging:
  file:
    path: ./logs/spring/logfile.log
  level.com.dms.pms.error: ERROR

dms:
  datasource:
    jdbc-url: ${DB_DMS_URL}
    username: ${DB_DMS_USERNAME:root}
    password: ${DB_DMS_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

auth:
  jwt:
    secret: ${JWT_SECRET}
    accessExp: ${JWT_ACCESS_EXP}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}

  oauth:
    apple:
      keyId: ${APPLE_KEY_ID}
      teamId: ${APPLE_TEAM_ID}